[package]
name = "ykbf"
version = "0.1.0"
authors = ["Laurence Tratt <laurie@tratt.net>"]
license = "Apache-2.0/MIT"
edition = "2018"

[dependencies]
getopts = "0.2"
libc = "0.2"

[dev-dependencies]
tempfile = "3.0"
